# Generated by Django 5.2.1 on 2025-05-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_consulta"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormularioFinanzas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario_id", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=100)),
                ("ingresos_mensuales", models.FloatField()),
                ("gasto_alimentacion", models.FloatField()),
                ("gasto_transporte", models.FloatField()),
                ("gasto_entretenimiento", models.FloatField()),
                ("meta_ahorro", models.FloatField()),
                ("ahorro_mensual", models.FloatField()),
                ("recomendaciones", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
