# Generated by Django 5.2.1 on 2025-05-26 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_formulariofinanzas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gastos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ahorro_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('meta_ahorro', models.DecimalField(decimal_places=2, max_digits=12)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GastoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='accounts.registrofinanciero')),
            ],
        ),
    ]
