# Generated by Django 5.2.1 on 2025-05-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_registrofinanciero_gastocategoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariofinanzas",
            name="gasto_hogar",
            field=models.FloatField(default=0),
        ),
    ]
