# Generated by Django 5.2.1 on 2025-05-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_formulariofinanzas_gasto_hogar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariofinanzas",
            name="usuario_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
