# Generated by Django 5.2.1 on 2025-05-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_formulariofinanzas_usuario_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulariofinanzas",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="formulariofinanzas",
            name="fecha_actualizacion",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="formulariofinanzas",
            name="ahorro_mensual",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="formulariofinanzas",
            name="gasto_alimentacion",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="formulariofinanzas",
            name="gasto_entretenimiento",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="formulariofinanzas",
            name="gasto_hogar",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="formulariofinanzas",
            name="gasto_transporte",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="formulariofinanzas",
            name="ingresos_mensuales",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="formulariofinanzas",
            name="meta_ahorro",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="formulariofinanzas",
            name="usuario_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
